# docker-compose.yml
 
# Reference compose file version 3
version: “3”
services:
# Service name is react-app
  react-app:
# build from Dockerfile
    build: .
# expose 80 as hosting port & 3000 in container port
    ports:
    - 80:3000
